const ADD_CART = "ADD_CART";
const RESET_CART = "RESET_CART";
const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
const ADD_CART_ERROR = "ADD_CART_ERROR";
const UPDATE_CART = "UPDATE_CART";
const REQUEST = "REQUEST";
const FETCH_CART = "FETCH_CART";
const DELETE_CART = "DELETE_CART";
const LOADING_REQUEST = "LOADING_REQUEST";
const LOADING_SUCCESS = "LOADING_SUCCESS";

export {
  REQUEST,
  ADD_CART,
  RESET_CART,
  ADD_CART_SUCCESS,
  ADD_CART_ERROR,
  UPDATE_CART,
  FETCH_CART,
  DELETE_CART,
  LOADING_REQUEST,
  LOADING_SUCCESS,
};
