const ADD_CHECKOUT_DETAIL = "ADD_CHECKOUT_DETAIL";
const ADD_CHECKOUT_SHIPPING = "ADD_CHECKOUT_SHIPPING";
const ADD_CHECKOUT_PAYMENT = "ADD_CHECKOUT_PAYMENT";
const ADD_CHECKOUT_DISCOUNT = "ADD_CHECKOUT_DISCOUNT";

const RESET_CHECKOUT = "RESET_CHECKOUT";
const UPDATE_CHECKOUT = "UPDATE_CHECKOUT";
const FETCH_CHECKOUT = "FETCH_CHECKOUT";

export {
    ADD_CHECKOUT_DETAIL,
    ADD_CHECKOUT_SHIPPING,
    ADD_CHECKOUT_PAYMENT,
    RESET_CHECKOUT,
    UPDATE_CHECKOUT,
    FETCH_CHECKOUT,
    ADD_CHECKOUT_DISCOUNT,
};
