export const ADD_WISHLIST = "ADD_WISHLIST";
export const FETCH_WISHLIST = "FETCH_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";
export const RESET_WISHLIST = "RESET_WISHLIST";
export const REQUEST = "REQUEST";
export const SUCCESS = "SUCCESS";
